name = "lifefarm"
author = "imoutopia"
version = "1.0.0+20261004.Release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6faff71ee4167a72ef5ac925209155bb12801b300d8b8de4f9de0359b17e9166"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.17", "1.21.5"]
