# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
maxParticlesPerSheet = 16384
particleRenderDistanceMultiplier = 1.0
asynchronousTicking = true
cullingBlacklist = [  ]
cullingBehavior = "AGGRESSIVE"
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "NONE"
]

[byTypeReductions]
"minecraft:ash" = 0.75
"minecraft:crimson_spore" = 0.75
"minecraft:warped_spore" = 0.75
"minecraft:white_ash" = 0.75